package com.hr.myrx2andgreendao3.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hr.myrx2andgreendao3.entiy.Dog;
import com.hr.myrx2andgreendao3.entiy.User;

import com.hr.myrx2andgreendao3.dao.DogDao;
import com.hr.myrx2andgreendao3.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dogDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DogDao dogDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dogDaoConfig = daoConfigMap.get(DogDao.class).clone();
        dogDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        dogDao = new DogDao(dogDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Dog.class, dogDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        dogDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DogDao getDogDao() {
        return dogDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
